spring:
  application:
    name: team-conect
  datasource:
    url: "jdbc:postgresql://ep-spring-sound-a5808511.us-east-2.aws.neon.tech/music-shop-group-3"
    username: music-shop_owner
    password: ZXIr9QuGR3Mt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

twilio:
  account_sid: "ACa76ab22c34db6dc67da37da09c7044f9"
  auth_token: "96b687d4e2e75a270330883155ba5dec"
  phone_number: "+12569524591"
