spring:
  spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/communication-delegation
  websocket:
    message-broker:
      application-destination-prefix: /app

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      boot:
        allow_jdbc_metadata_access: false
  sql:
    init:
      mode: never

      twilio:
  twilio:
  account_sid: "ACa76ab22c34db6dc67da37da09c7044f9"
  auth_token: "96b687d4e2e75a270330883155ba5dec"
  phone_number: "+12569524591"

